# This is a basic workflow to help you get started with Actions
name: Sync from upstream

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/netrisai/netris-operator"
        source_branch: "master"
        destination_branch: "master"
        sync_tags: ""
        github_token: ${{ secrets.MIRROR }}
